tests: Fix clang initialization error.
The following compile-time error occurs in tests/test-sockaddr.c when
building mptcpd with clang 14:

    error: initializer element is not a compile-time constant

Drop the "static" storage qualifier as needed to address this error.