ell: only include 'ell/ell.h' header
When looking at the code of other projects using ELL (IWD, BlueZ,
Ofono), it looks like only 'ell.h' should be included, not individual
header files from the 'ell' header directory.

That looks like the way to go, because when looking at ell/genl.h, it
uses functions declared in ell/netlink.h, without including this file
before. This causes issues when compiling the code using libell-dev
installed on the system:

  libtool: compile:  gcc (...) -c path_manager.c (...)
  In file included from path_manager.c:21:
  /usr/include/ell/genl.h: In function 'l_genl_attr_next':
  /usr/include/ell/genl.h:98:16: error: implicit declaration of function 'l_netlink_attr_next'; did you mean 'l_genl_attr_next'? [-Wimplicit-function-declaration]
     98 |         return l_netlink_attr_next((struct l_netlink_attr *) attr,
        |                ^~~~~~~~~~~~~~~~~~~
        |                l_genl_attr_next
  /usr/include/ell/genl.h: In function 'l_genl_attr_recurse':
  /usr/include/ell/genl.h:105:16: error: implicit declaration of function 'l_netlink_attr_recurse'; did you mean 'l_genl_attr_recurse'? [-Wimplicit-function-declaration]
    105 |         return l_netlink_attr_recurse((struct l_netlink_attr *) attr,
        |                ^~~~~~~~~~~~~~~~~~~~~~
        |                l_genl_attr_recurse
  make[2]: *** [Makefile:597: libmptcpd_la-path_manager.lo] Error 1

All .c files including ELL header files have been modified to include
only <ell/ell.h>. The .cpp file in the tests has not been modified,
because it looks like that causes some issues. For the same reason,
include/mptcpd/private/plugin.h file has not been modified as well.

Closes: #302
Signed-off-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>